[package]
name = "evops-pb-ext"
edition = "2024"

[dependencies]
evops-models = { workspace = true }

# Needed by build.rs.
prost = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
